spring:
  application:
    name: todo-app
  datasource:
    driver-class-name: org.postgresql.Driver
    username: cris
    password: admin
    url: "jdbc:postgresql://localhost:5432/MY_ECOMMERCE"
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    database: POSTGRESQL
